<?php

namespace Database\Seeders;

use App\Models\Kebijakan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class KebijakanSeeder extends Seeder
{
    public function run(): void
    {
        Kebijakan::query()->delete();

        $kebijakans = [
            [
                'title' => 'Kerahasiaan Username & Password Akun',
                'slug' => 'kebijakan-kerahasiaan-username-password',
                'for_role' => 'all',
                'content' => "## 1. Pendahuluan\nKeamanan akun pengguna adalah tanggung jawab bersama. Kebijakan ini mengatur kewajiban setiap pengguna SIAKAD SMAN 1 Tuhemberua dalam menjaga kerahasiaan kredensial masuk.\n\n## 2. Kewajiban Pengguna\nSetiap pengguna (Admin, Guru, Siswa, Kepala Sekolah, Tenaga Kependidikan) WAJIB:\n\n- **TIDAK MEMBAGIKAN** username dan password akun kepada siapa pun dengan alasan apa pun, termasuk:\n  - Teman sekelas / rekan sejawat\n  - Orang tua / wali murid\n  - Bahkan operator sekolah / Admin resmi\n- **MENJAGA KERAHASIAAN** password. Gunakan kombinasi minimal 8 karakter, campuran huruf besar+ kecil, angka, dan simbol jika memungkinkan.\n- **SEGERA MENGGANTI PASSWORD** setelah menerima password reset dari Admin melalui menu Profil > Ubah Password.\n- **LOGOUT DENGAN BENAR** setiap kali selesai menggunakan, terutama pada komputer umum (laboratorium, perpustakaan, warnet) dan perangkat milik bersama.\n- **MEMAKAI PERANGKAT PRIBADI** yang terjamin keamanannya (tidak di-root/jailbreak, memiliki antivirus, OS selalu diperbarui).\n\n## 3. Sanksi Pelanggaran\nPengguna yang terbukti dengan sengaja membagikan akun sehingga disalahgunakan pihak ketiga, akan dikenakan:\n1. Peringatan tertulis / notifikasi sistem.\n2. Pemutusan akses SIAKAD (status akun = **INACTIVE**) sementara.\n3. Pertanggungjawaban jika terjadi kerugian materiil / immaterial akibat penyalahgunaan akun tersebut.\n\n## 4. Tanggung Jawab Sistem\n- Password disimpan dengan metode **HASH Bcrypt** (satu arah). Artinya BAHKAN ADMIN PUN TIDAK BISA MEMBACA password asli Anda.\n- Jika lupa password, satu-satunya prosedur adalah **RESET PASSWORD** oleh Admin melalui menu User & Akses > Reset Password.\n- Sistem membatasi percobaan login gagal (Rate Limiter: 5 kali / 60 detik per username + IP).",
            ],
            [
                'title' => 'Larangan Menggunakan Akun Milik Orang Lain',
                'slug' => 'kebijakan-larangan-akun-orang-lain',
                'for_role' => 'all',
                'content' => "## 1. Dasar Kebijakan\nSetiap akun SIAKAD adalah **pribadi dan TIDAK DIPINDAHTANGANKAN**.\n\n## 2. Perbuatan yang DILARANG KERAS\nDengan ini tegas dilarang:\n\n### 2.1 Login Menggunakan Akun Orang Lain\n❌ Siswa login menggunakan akun Guru / temannya untuk melihat nilai lebih awal.\n❌ Guru login menggunakan akun Admin untuk mengubah data master yang bukan wewenangnya.\n❌ Orang tua login menggunakan akun anaknya tanpa sepengetahuan sekolah.\n❌ Siapapun yang mencoba menebak password akun orang lain (Brute Force Attack).\n\n### 2.2 Menyewakan / Menjual Akun\n❌ Menjual akun dengan nilai tinggi, menyewakan untuk jasa input nilai, dll.\n\n### 2.3 \"Titip Login\" Ke Teman\n❌ \"Titip ya, nanti saya ada rapat, tolong buka akun saya untuk input nilai\".\nGunakan fitur Delegasi (jika tersedia) atau koordinasi ke Admin untuk perizinan khusus.\n\n## 3. Deteksi Pelanggaran\nSistem secara otomatis mencatat setiap aktivitas login di **Log Sistem** (timestamp, alamat IP, User Agent browser):\n- Login bersamaan dari 2+ lokasi geografis berbeda dalam waktu < 5 menit = flag otomatis.\n- Percobaan login dengan password salah berulang (Rate Limiter).\n- Perubahan data penting yang tidak sesuai role = flag audit Admin.\n\n## 4. Sanksi\n1. Peringatan 1.\n2. Akun **SUSPEND / INACTIVE** 3 – 14 hari kerja.\n3. Pengembalian / pemulihan data yang diubah tanpa hak.\n4. Kasus berat diserahkan kepada BK / Tata Usaha / pihak berwajib.",
            ],
            [
                'title' => 'Hak Akses Fitur Sesuai Peran (RBAC)',
                'slug' => 'kebijakan-hak-akses-sesuai-peran',
                'for_role' => 'all',
                'content' => "## 1. Prinsip *Least Privilege*\nSIAKAD menerapkan **RBAC (Role-Based Access Control)** berlapis. Setiap pengguna HANYA DIBERIKAN hak akses sesuai kebutuhan pekerjaannya. TIDAK ADA pengguna yang punya akses penuh selain peran **Administrator** yang ditunjuk.\n\n## 2. Pembagian Peran & Akses Utama\n\n| Peran | Fitur Utama yang Diizinkan |\n| --- | --- |\n| **Administrator** | Semua fitur. CRUD data master (Guru, Siswa, Kelas, Mapel, Jadwal), Verifikasi & Reset Password user, Manage Pengumuman, Kelola FAQ & Kebijakan, Tanggapi Laporan Masalah. |\n| **Guru** | Lihat Jadwal Mengajar, Input/Edit Nilai mapel yang diampu, Absensi kelas, Lihat Profil & ubah data diri sendiri. |\n| **Siswa** | Lihat Nilai, Lihat Jadwal Pelajaran, Lihat Absensi & Riwayat Absen, Unduh Raport, Kirim Laporan Masalah, Ubah Profil. |\n| **Kepala Sekolah** | Dashboard Monitoring, Laporan Akademik, Laporan Nilai & Absensi, Verifikasi Raport. |\n| **Tenaga Kependidikan (Tendik)** | Terbatas sesuai penunjukan Admin (TU, BK, dsb). |\n\n## 3. Larangan Teknis\n- **Siswa / Guru TIDAK BOLEH** memaksa mengakses URL /admin/... dengan mengetik manual di address bar. Middleware `CheckRole` akan memblokir, logout paksa, dan mencatat IP user.\n- **Siswa TIDAK BOLEH** edit data siswa lain, input / edit / hapus nilai.\n- **Guru TIDAK BOLEH** approve user, reset password user lain, mengubah jadwal tanpa sepengetahuan Admin.\n\n## 4. Pengajuan Kenaikan Hak Akses\nJika Anda membutuhkan akses fitur tapi belum punya izin (misal Tendik baru butuh akses input data siswa):\n1. Kirim **Laporan Masalah** → kategori **Saran** atau **Masalah Akses**.\n2. Lampirkan bukti Surat Tugas / SK dari Kepala Sekolah.\n3. Admin akan review 1x24 jam, jika disetujui peran Anda akan diupdate.",
            ],
            [
                'title' => 'Kewenangan Pengelolaan Data Akademik',
                'slug' => 'kebijakan-wewenang-data-akademik',
                'for_role' => 'all',
                'content' => "## 1. Ruang Lingkup\nData akademik meliputi: Nilai (Harian, Tugas, UTS, UAS, Raport), Absensi, Jadwal Pelajaran, Kelas & Mata Pelajaran, Identitas Siswa & Guru.\n\n## 2. Pemisahan Wewenang (Segregation of Duties)\n\n| Data Siapa yang Mengelola | Data |\n| --- | --- |\n| **Admin** | Data Master: User (Verifikasi), Kelas, Ruangan, Tahun Ajaran, Semester, Mapel, Jadwal Pelajaran (tambah/edit/hapus), Pengumuman. Publish akhir Raport. |\n| **Guru Mapel Bersangkutan** | Input nilai HANYA mapel yang diajar dan kelas yang diajar (tidak bisa mapel lain). Edit/Perbaiki nilai yang bersangkutan. Input absensi siswa di kelasnya. |\n| **Wali Kelas** | Validasi data siswa di kelas binaan, Menulis catatan wali kelas, Persetujuan laporan absensi kelas. |\n| **Siswa** | HANYA MELIHAT data diri sendiri (nilai, jadwal, absensi, raport). Edit terbatas data Profil Pribadi (No HP, Alamat). |\n| **Kepala Sekolah** | Monitor & validasi laporan. Verifikasi tanda tangan raport. **TIDAK** mengubah data input Guru tanpa proses rapat.\n\n## 3. Alur Perbaikan / Koreksi Data\nContoh kasus: salah input nilai 88 → 98\n1. **Siswa melaporkan** ke Guru Mapel bersangkutan (ditembuskan ke Admin via Bantuan > Lapor Masalah kategori Data Akademik).\n2. **Guru Mapel** → buka Input Nilai, edit angka → Simpan. Notifikasi Admin akan muncul kembali untuk review perubahan nilai.\n3. Jika melebihi batas waktu input (tutup semester):\n   → hanya **Admin** yang bisa override perubahan nilai dengan menyertakan Berita Acara Koreksi dari Guru Mapel + Kepala Sekolah.\n\n## 4. Audit Trail\nSetiap perubahan nilai menyimpan: who, what, when, from → to. Dapat diaudit Admin sewaktu-waktu untuk laporan Dinas Pendidikan / audit eksternal.",
            ],
            [
                'title' => 'Larangan Akses Halaman / Data Luar Wewenang',
                'slug' => 'kebijakan-larangan-akses-tidak-berwenang',
                'for_role' => 'all',
                'content' => "## 1. Tujuan\nMelindungi data pribadi siswa/guru dan integritas data akademik dari upaya akses tidak sah.\n\n## 2. Perbuatan yang Dilarang (dan Otomatis Diblokir)\nBerikut perbuatan yang **dilarang** dan OTOMATIS DIBLOKIR middleware SIAKAD + tercatat di log sistem:\n\n### 2.1 URL Manipulasi (Force Browse)\nMencoba mengetik URL yang bukan haknya di address bar, misal:\n• Siswa → `/admin/dashboard`\n• Guru → `/admin/verifikasi-pengguna`\n• Guest → `/notifikasi`\n\n### 2.2 Mengutak-atik Param ID di URL
Mengubah parameter ID (misal `?user_id=X` → `?user_id=TEMAN`) untuk melihat data orang lain. Kebanyakan halaman SIAKAD menggunakan **Ownership Scope** (`\$query->where('user_id', Auth::id())`) sehingga akan membalik 404 Not Found.\n\n### 2.3 Percobaan \"SQL Injection\" / XSS via Input Form\nMencoba memasukkan string berbahaya di form (Lapor Masalah, ubah profil, dll). Laravel otomatis sanitasi dengan Eloquent Prepared Statements & Blade double-curly braces. Pelanggar berat akan otomatis trigger rate limiter = IP blokir sementara.\n\n### 2.4 Sharing Session / Cookie Login\nMencoba menyalin value Cookie / Session dari perangkat A ke perangkat B. Session di SIAKAD terikat kombinasi User-Agent + IP + regenerate ID setiap login & logout.\n\n## 3. Konsekuensi\n1. Percobaan ke-1 & ke-2: Logout paksa otomatis.\n2. Percobaan berulang (≥5 kali/hari): **IP Address** otomatis diblokir rate limiter 60 menit.\n3. Admin menerima notifikasi flag \"Aktivitas Mencurigakan\".\n4. Kasus terbukti disengaja: pemutusan akses permanen + laporan ke pihak berwajib jika ada kerugian.",
            ],
            [
                'title' => 'Penggunaan Sistem Untuk Kepentingan Akademik Saja',
                'slug' => 'kebijakan-penggunaan-akademik',
                'for_role' => 'all',
                'content' => "## 1. Tujuan Penggunaan Sistem\nSistem Informasi Akademik (SIAKAD) SMAN 1 Tuhemberua disediakan **KHUSUS** untuk mendukung kegiatan TRI DHARMA pendidikan di SMA Negeri 1 Tuhemberua:\n1. **PENDIDIKAN** (proses KBM, penilaian, absensi)\n2. **PENELITIAN** (analisis data akademik untuk guru)\n3. **PENGABDIAN** (layanan data akademik kepada orang tua / wali)\n\n## 2. Hal yang DILARANG menggunakan SIAKAD\n❌ Mengupload file pendukung Laporan Masalah berisi:\n   • Konten ilegal, SARA, pornografi, perjudian\n   • Malware / virus\n   • File bajakan (film, musik, software)\n   • Hoax, fitnah, pencemaran nama baik\n\n❌ Menggunakan nama / status akun SIAKAD untuk transaksi jual-beli di luar kepentingan sekolah.\n\n❌ Mengirim spam melalui fitur komentar / laporan / saran.\n\n❌ Melakukan DDOS, membebani server dengan refresh halaman ribuan kali / script otomatis.\n\n## 3. Etika Penggunaan Forum / Fitur Komunikasi\nJika tersedia fitur Pengumuman interaktif / komentar:\n• Gunakan Bahasa Indonesia yang baik dan benar.\n• Hindari kata-kata kotor, kasar, mendiskriminasi SARA / 3R.\n• Berikan kritik & saran yang MEMBANGUN, bukan menjatuhkan.\n\n## 4. Sanksi Pelanggaran\n1. File upload yang melanggar → otomatis dihapus Admin + notifikasi peringatan.\n2. Konten SARA / pencemaran → akun INACTIVE + panggilan orang tua / BK.\n3. Kerugian materiil / kejahatan → dilaporkan ke pihak kepolisian sesuai Undang-Undang ITE Nomor 19 Tahun 2016.",
            ],
            [
                'title' => 'Kebijakan Privasi & Perlindungan Data Pribadi',
                'slug' => 'kebijakan-privasi-data',
                'for_role' => 'all',
                'content' => "## 1. Komitmen Sekolah\nSMAN 1 Tuhemberua berkomitmen penuh melindungi Data Pribadi Pengguna (Siswa, Guru, Orang Tua) sesuai:\n• **UU No. 27 Tahun 2022 tentang Perlindungan Data Pribadi (UU PDP)**\n• **Permendikbudristek tentang Pengelolaan Data Pendidikan**\n• **Standar ISO 27001 (jika memungkinkan)**\n\n## 2. Data Pribadi Yang Dikumpulkan\n| Kategori | Data |\n| --- | --- |\n| **Autentikasi** | Username, email, hash password (TIDAK PERNAH plaintext) |\n| **Siswa** | Nama Lengkap, Tempat/Tanggal Lahir, Jenis Kelamin, NIS/NISN (jika ada), Kelas, Alamat, Nama Orang Tua/Wali, No HP Orang Tua |\n| **Guru** | Nama Lengkap, NIP (jika ada), Gelar Depan/Belakang, Jenis Kelamin, No HP, Alamat, Mapel yang Diampu |\n| **Log Sistem** | Waktu login, IP Address, User Agent Browser, Halaman yang diakses |\n| **Laporan Masalah** | Subjek, Deskripsi, File Pendukung, Respon Admin |\n\n## 3. Tujuan Penggunaan Data\nData hanya digunakan untuk:\n✅ Proses belajar-mengajar (nilai, jadwal, absensi, raport)\n✅ Komunikasi pengumuman sekolah\n✅ Laporan kepada Dinas Pendidikan Propinsi / Kabupaten\n✅ Layanan Bantuan & Laporan Masalah\n✅ Audit internal mutu sekolah\n\n## 4. Data TIDAK AKAN diberikan kepada:\n❌ Pihak ketiga yang tidak memiliki kerjasama tertulis dengan sekolah (Iklan, Marketing, Pinjol, dll)\n❌ Individu tanpa dasar hukum yang kuat\n\n## 5. Hak Subjek Data\nSetiap Siswa/Guru (selaku Subjek Data) berhak:\n1. **Melihat** data sendiri di Profil\n2. **Meminta koreksi** data jika salah via Laporan Masalah kategori Data Akademik\n3. **Meminta penghapusan** data sesuai ketentuan (kelulusan / mutasi sekolah / mengundurkan diri) melalui permohonan tertulis ke Kepala Sekolah\n\n## 6. Masa Retensi Data\n- Data Siswa Aktif: disimpan selama menjadi siswa\n- Data Alumni: 10 tahun setelah kelulusan untuk keperluan ijazah / legalisir\n- Data Guru Aktif: selama menjadi guru\n- Data Guru Pensiun / Pindah Tugas: 5 tahun masa arsip aktif → pindah arsip statis.\n\n## 7. Keluhan Privasi\nKirim email DPO (Data Protection Officer) sekolah ke **admin@sman1tuhemberua.sch.id** dengan subject: **KEBERATAN PRIVASI**. Anda akan menerima jawaban paling lambat 14 hari kalender.",
            ],
            [
                'title' => 'Syarat & Ketentuan Umum Penggunaan SIAKAD',
                'slug' => 'syarat-dan-ketentuan-umum',
                'for_role' => 'all',
                'content' => "## 1. Penerimaan Syarat\nDengan **MENDAFTAR / LOGIN** ke SIAKAD SMAN 1 Tuhemberua, Anda secara tegas **MENYETUJUI** seluruh Syarat & Ketentuan berikut serta Kebijakan Privasi dan 7 Kebijakan Sistem lain yang berlaku.\n\nJika Anda **TIDAK SETUJU**, harap segera keluar dari sistem dan hubungi Admin.\n\n## 2. Perubahan Syarat & Ketentuan\nPihak Sekolah sewaktu-waktu dapat memperbarui isi Syarat & Ketentuan ini tanpa pemberitahuan personal terlebih dahulu.\n- Pengumuman perubahan ditampilkan di halaman Pengumuman Utama.\n- Penggunaan berkelanjutan setelah perubahan = dianggap menerima syarat baru.\n\n## 3. Ketersediaan Layanan (SLA)\nLayanan SIAKAD berusaha tersedia 24/7, namun kami **TIDAK MENJAMIN**:\n• Selalu tersedia 100% (terdapat jadwal maintenance rutin)\n• Tidak terjadi error / bug\n• Kecepatan akses sama di semua provider ISP\n\nSLA Target: Uptime ≥ 99% per bulan.\nJadwal Maintenance: Minggu malam pk. 22.00 – 24.00 WIB.\n\n## 4. Batasan Tanggung Jawab\nPihak Sekolah **TIDAK BERTANGGUNG JAWAB** atas:\n• Kerugian akibat koneksi internet Anda terputus saat submit form.\n• Kesalahan input data yang dilakukan oleh pengguna sendiri.\n• Kelalaian pengguna menjaga kerahasiaan password.\n• Virus / malware di perangkat pengguna yang merusak data lokal.\n• Force Majeure (bencana alam, pemadaman listrik total, provider internet down nasional, perang, dll).\n\n## 5. Hak Kekayaan Intelektual\nSeluruh source code, desain UI/UX, logo, nama merek \"SIAKAD SMAN 1 Tuhemberua\", struktur database, merupakan aset intelektual sekolah.\nDengan ini dilarang:\n❌ Menduplikasi, menjual, menyewakan source code tanpa ijin tertulis Kepala Sekolah\n❌ Membuat kloningan / tiruan sistem dengan nama mirip untuk menipu siswa / wali\n\n## 6. Hukum Yang Berlaku\nSyarat & Ketentuan ini tunduk pada hukum Negara Kesatuan Republik Indonesia.\nSegala sengketa yang tidak dapat diselesaikan secara kekeluargaan, pertama-tama diajukan ke **Mediasi Dinas Pendidikan** setempat sebelum menempuh jalur perdata / pidana di Pengadilan Negeri setempat.\n\n## 7. Kontak\nUntuk pertanyaan seputar syarat ini: **Bantuan > Laporkan Masalah** atau email **admin@sman1tuhemberua.sch.id**.\n\nTerakhir diperbarui: " . now()->format('d F Y') . ".",
            ],
        ];

        foreach ($kebijakans as $kb) {
            Kebijakan::create($kb);
        }
    }
}
